Can't import srv:
Traceback (most recent call last):
  File "./src/make_marker.py", line 10, in <module>
    from rviz.srv import *
ImportError: No module named srv

So it needs to go into entirely different package?